### ISSUE TITLE
unexpected behavior Result::as_array()

### ISSUE THREAD

**Issue by alameya** [PHPixie/Project#25]
DB::as_array() returns Array of Objects but should return array of arrays like in kohana...

**Comment by dracony** [comment]
use as_array(true) to get array of arrays =)

**Comment by alameya** [comment]
oh, tnx!

**Comment by alameya** [comment]
may i am stupid...
but
 (new DB($this->pixie))->query(
            'select',
            'slave_1'
        )
            ->table($this->table)
        ->execute()
        ->as_array(true);
return array of objects

**Comment by dracony** [comment]
Ah I thought you were referring to ORM Results and ORM Objects. Yes DB rows are always returned as objects is there any reason you would want those as arrays? You can always cast (array) on them to get an array.

**Comment by alameya** [comment]
Yes, i did it.
I need arrays for template class.
Any way ty for your job)

**Comment by dracony** [comment]
is it a custom class? I mean if you could rewrite it to use objects it would be great =)
But if  some external library requires an array I could add a parameter to return an array of arrays. But you'd face same problems in your templating when using ORM models for the same reason (since models are objects)

**Comment by alameya** [comment]
it's blitz template alternate syntax...
http://alexeyrybak.com/blitz/blitz_en.html
