### ISSUE TITLE
Dynamically use 'partial' with HAML

### ISSUE THREAD

**Issue by aszkid** [PHPixie/Project#8]
Is there any way i can use a PHP variable to dynamically use the 'partial' tool in the HAML files i create?

I've tried a bunch of things, but things like this

```
 partial:$foo
```

or

```
 echo "partial:{$foo}"
```

don't work.

Event the one you posted here: http://phpixie.com/modules/haml-module/#highlighter_62632 fails, because it gets the literal value, not the variable that's holding it.

**Comment by dracony** [comment]
Hm, yup there is a problem here. It's rather hard to solve because partials get parsed before haml is executed, so that variable doesn't really have a value at the time. The only solution to this would be adding a new static method e.g. load_partial, that you could call from haml like this:
- HAML::load_partial($template_name,get_defined_vars());
  I'll try that out tomorrow, and perhaps find a prettier way without having to use get_defined_vars()

**Comment by dracony** [comment]
http://phpixie.com/blog/dynamic-partials-in-haml-templates/
Done that =)
